//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook
{
    using System;
    using System.Collections.Generic;
    using PhoneBook.Models;
    
    public partial class Contact : BaseEntity 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public byte[] Avatar { get; set; }
        public string Address { get; set; }
    }
}
